### ISSUE TITLE
Error while running make

### ISSUE THREAD

**Issue by philogb** [ilyabo/openvis-react#1]
```
$ make
node --harmony ./node_modules/.bin/grunt --gruntfile make.js serve
Loading "make.js" tasks...ERROR
>> Error: Cannot find module './webpack.dist.config.js'
Warning: Task "serve" not found. Use --force to continue.

Aborted due to warnings.
make: *** [server] Error 3
```

**Comment by ilyabo** [comment]
should work now.
thanks nicolas!

**Comment by philogb** [comment]
thanks!

2015-04-09 12:15 GMT-07:00 Ilya Boyandin notifications@github.com:

> should work now.
> thanks nicolas!
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/ilyabo/openvis-react/issues/1#issuecomment-91331905.

## 

Nicolas Garcia Belmonte - http://philogb.github.com/
